// Country coverage comes from the public-domain IANA zone.tab and iso3166.tab
// shipped in /usr/share/zoneinfo (snapshot October 2026), with curated major cities.
// https://data.iana.org/time-zones/tzdb/zone.tab
// https://data.iana.org/time-zones/tzdb/iso3166.tab
// This is a selection list, not a complete historical-zone catalog. Exact valid
// device/saved zones are retained separately; no zones are remapped by offset.

const US_OPTIONS = [
  ["America/New_York", "Eastern Time — New York"],
  ["America/Chicago", "Central Time — Chicago"],
  ["America/Denver", "Mountain Time — Denver"],
  ["America/Los_Angeles", "Pacific Time — Los Angeles"],
  ["America/Anchorage", "Alaska Time — Anchorage"],
  ["Pacific/Honolulu", "Hawaii Time — Honolulu"],
  ["America/Phoenix", "Arizona Time — Phoenix"],
  ["America/Adak", "Aleutian Time — Adak"],
];

// One representative for every country/territory with a zone.tab entry, plus
// useful regional choices where modern clock rules differ.
const COUNTRY_ZONES = [
  ["Afghanistan", "Asia/Kabul"],
  ["Albania", "Europe/Tirane"],
  ["Algeria", "Africa/Algiers"],
  ["American Samoa", "Pacific/Pago_Pago"],
  ["Andorra", "Europe/Andorra"],
  ["Angola", "Africa/Luanda"],
  ["Anguilla", "America/Anguilla"],
  ["Antarctica", "Antarctica/McMurdo"],
  ["Antigua & Barbuda", "America/Antigua"],
  ["Argentina", "America/Argentina/Buenos_Aires"],
  ["Armenia", "Asia/Yerevan"],
  ["Aruba", "America/Aruba"],
  [
    "Australia",
    "Australia/Sydney",
    "Australia/Brisbane",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Australia/Perth",
    "Australia/Lord_Howe",
    "Australia/Eucla",
  ],
  ["Austria", "Europe/Vienna"],
  ["Azerbaijan", "Asia/Baku"],
  ["Bahamas", "America/Nassau"],
  ["Bahrain", "Asia/Bahrain"],
  ["Bangladesh", "Asia/Dhaka"],
  ["Barbados", "America/Barbados"],
  ["Belarus", "Europe/Minsk"],
  ["Belgium", "Europe/Brussels"],
  ["Belize", "America/Belize"],
  ["Benin", "Africa/Porto-Novo"],
  ["Bermuda", "Atlantic/Bermuda"],
  ["Bhutan", "Asia/Thimphu"],
  ["Bolivia", "America/La_Paz"],
  ["Bosnia & Herzegovina", "Europe/Sarajevo"],
  ["Botswana", "Africa/Gaborone"],
  [
    "Brazil",
    "America/Sao_Paulo",
    "America/Manaus",
    "America/Rio_Branco",
    "America/Noronha",
  ],
  ["British Indian Ocean Territory", "Indian/Chagos"],
  ["Brunei", "Asia/Brunei"],
  ["Bulgaria", "Europe/Sofia"],
  ["Burkina Faso", "Africa/Ouagadougou"],
  ["Burundi", "Africa/Bujumbura"],
  ["Cambodia", "Asia/Phnom_Penh"],
  ["Cameroon", "Africa/Douala"],
  [
    "Canada",
    "America/Toronto",
    "America/Halifax",
    "America/St_Johns",
    "America/Winnipeg",
    "America/Regina",
    "America/Edmonton",
    "America/Vancouver",
    "America/Whitehorse",
  ],
  ["Cape Verde", "Atlantic/Cape_Verde"],
  ["Caribbean NL", "America/Kralendijk"],
  ["Cayman Islands", "America/Cayman"],
  ["Central African Rep.", "Africa/Bangui"],
  ["Chad", "Africa/Ndjamena"],
  ["Chile", "America/Santiago", "America/Punta_Arenas", "Pacific/Easter"],
  ["China", "Asia/Shanghai", "Asia/Urumqi"],
  ["Christmas Island", "Indian/Christmas"],
  ["Cocos (Keeling) Islands", "Indian/Cocos"],
  ["Colombia", "America/Bogota"],
  ["Comoros", "Indian/Comoro"],
  ["Cook Islands", "Pacific/Rarotonga"],
  ["Costa Rica", "America/Costa_Rica"],
  ["Croatia", "Europe/Zagreb"],
  ["Cuba", "America/Havana"],
  ["Curaçao", "America/Curacao"],
  ["Cyprus", "Asia/Nicosia"],
  ["Czech Republic", "Europe/Prague"],
  ["Côte d’Ivoire", "Africa/Abidjan"],
  ["Democratic Republic of the Congo", "Africa/Kinshasa", "Africa/Lubumbashi"],
  ["Denmark", "Europe/Copenhagen"],
  ["Djibouti", "Africa/Djibouti"],
  ["Dominica", "America/Dominica"],
  ["Dominican Republic", "America/Santo_Domingo"],
  ["East Timor", "Asia/Dili"],
  ["Ecuador", "America/Guayaquil", "Pacific/Galapagos"],
  ["Egypt", "Africa/Cairo"],
  ["El Salvador", "America/El_Salvador"],
  ["Equatorial Guinea", "Africa/Malabo"],
  ["Eritrea", "Africa/Asmara"],
  ["Estonia", "Europe/Tallinn"],
  ["Eswatini (Swaziland)", "Africa/Mbabane"],
  ["Ethiopia", "Africa/Addis_Ababa"],
  ["Falkland Islands", "Atlantic/Stanley"],
  ["Faroe Islands", "Atlantic/Faroe"],
  ["Fiji", "Pacific/Fiji"],
  ["Finland", "Europe/Helsinki"],
  ["France", "Europe/Paris"],
  ["French Guiana", "America/Cayenne"],
  [
    "French Polynesia",
    "Pacific/Tahiti",
    "Pacific/Marquesas",
    "Pacific/Gambier",
  ],
  ["French S. Terr.", "Indian/Kerguelen"],
  ["Gabon", "Africa/Libreville"],
  ["Gambia", "Africa/Banjul"],
  ["Georgia", "Asia/Tbilisi"],
  ["Germany", "Europe/Berlin"],
  ["Ghana", "Africa/Accra"],
  ["Gibraltar", "Europe/Gibraltar"],
  ["Greece", "Europe/Athens"],
  ["Greenland", "America/Nuuk", "America/Danmarkshavn", "America/Thule"],
  ["Grenada", "America/Grenada"],
  ["Guadeloupe", "America/Guadeloupe"],
  ["Guam", "Pacific/Guam"],
  ["Guatemala", "America/Guatemala"],
  ["Guernsey", "Europe/Guernsey"],
  ["Guinea", "Africa/Conakry"],
  ["Guinea-Bissau", "Africa/Bissau"],
  ["Guyana", "America/Guyana"],
  ["Haiti", "America/Port-au-Prince"],
  ["Honduras", "America/Tegucigalpa"],
  ["Hong Kong", "Asia/Hong_Kong"],
  ["Hungary", "Europe/Budapest"],
  ["Iceland", "Atlantic/Reykjavik"],
  ["India", "Asia/Kolkata"],
  ["Indonesia", "Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"],
  ["Iran", "Asia/Tehran"],
  ["Iraq", "Asia/Baghdad"],
  ["Ireland", "Europe/Dublin"],
  ["Isle of Man", "Europe/Isle_of_Man"],
  ["Israel", "Asia/Jerusalem"],
  ["Italy", "Europe/Rome"],
  ["Jamaica", "America/Jamaica"],
  ["Japan", "Asia/Tokyo"],
  ["Jersey", "Europe/Jersey"],
  ["Jordan", "Asia/Amman"],
  ["Kazakhstan", "Asia/Almaty"],
  ["Kenya", "Africa/Nairobi"],
  ["Kiribati", "Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"],
  ["Kuwait", "Asia/Kuwait"],
  ["Kyrgyzstan", "Asia/Bishkek"],
  ["Laos", "Asia/Vientiane"],
  ["Latvia", "Europe/Riga"],
  ["Lebanon", "Asia/Beirut"],
  ["Lesotho", "Africa/Maseru"],
  ["Liberia", "Africa/Monrovia"],
  ["Libya", "Africa/Tripoli"],
  ["Liechtenstein", "Europe/Vaduz"],
  ["Lithuania", "Europe/Vilnius"],
  ["Luxembourg", "Europe/Luxembourg"],
  ["Macau", "Asia/Macau"],
  ["Madagascar", "Indian/Antananarivo"],
  ["Malawi", "Africa/Blantyre"],
  ["Malaysia", "Asia/Kuala_Lumpur"],
  ["Maldives", "Indian/Maldives"],
  ["Mali", "Africa/Bamako"],
  ["Malta", "Europe/Malta"],
  ["Marshall Islands", "Pacific/Majuro"],
  ["Martinique", "America/Martinique"],
  ["Mauritania", "Africa/Nouakchott"],
  ["Mauritius", "Indian/Mauritius"],
  ["Mayotte", "Indian/Mayotte"],
  [
    "Mexico",
    "America/Mexico_City",
    "America/Cancun",
    "America/Mazatlan",
    "America/Tijuana",
    "America/Ciudad_Juarez",
    "America/Matamoros",
  ],
  ["Micronesia", "Pacific/Chuuk"],
  ["Moldova", "Europe/Chisinau"],
  ["Monaco", "Europe/Monaco"],
  ["Mongolia", "Asia/Ulaanbaatar", "Asia/Hovd"],
  ["Montenegro", "Europe/Podgorica"],
  ["Montserrat", "America/Montserrat"],
  ["Morocco", "Africa/Casablanca"],
  ["Mozambique", "Africa/Maputo"],
  ["Myanmar (Burma)", "Asia/Yangon"],
  ["Namibia", "Africa/Windhoek"],
  ["Nauru", "Pacific/Nauru"],
  ["Nepal", "Asia/Kathmandu"],
  ["Netherlands", "Europe/Amsterdam"],
  ["New Caledonia", "Pacific/Noumea"],
  ["New Zealand", "Pacific/Auckland", "Pacific/Chatham"],
  ["Nicaragua", "America/Managua"],
  ["Niger", "Africa/Niamey"],
  ["Nigeria", "Africa/Lagos"],
  ["Niue", "Pacific/Niue"],
  ["Norfolk Island", "Pacific/Norfolk"],
  ["North Korea", "Asia/Pyongyang"],
  ["North Macedonia", "Europe/Skopje"],
  ["Northern Mariana Islands", "Pacific/Saipan"],
  ["Norway", "Europe/Oslo"],
  ["Oman", "Asia/Muscat"],
  ["Pakistan", "Asia/Karachi"],
  ["Palau", "Pacific/Palau"],
  ["Palestine", "Asia/Gaza"],
  ["Panama", "America/Panama"],
  ["Papua New Guinea", "Pacific/Port_Moresby", "Pacific/Bougainville"],
  ["Paraguay", "America/Asuncion"],
  ["Peru", "America/Lima"],
  ["Philippines", "Asia/Manila"],
  ["Pitcairn", "Pacific/Pitcairn"],
  ["Poland", "Europe/Warsaw"],
  ["Portugal", "Europe/Lisbon", "Atlantic/Azores"],
  ["Puerto Rico", "America/Puerto_Rico"],
  ["Qatar", "Asia/Qatar"],
  ["Republic of the Congo", "Africa/Brazzaville"],
  ["Romania", "Europe/Bucharest"],
  [
    "Russia",
    "Europe/Moscow",
    "Europe/Kaliningrad",
    "Europe/Samara",
    "Asia/Yekaterinburg",
    "Asia/Omsk",
    "Asia/Novosibirsk",
    "Asia/Irkutsk",
    "Asia/Yakutsk",
    "Asia/Vladivostok",
    "Asia/Magadan",
    "Asia/Kamchatka",
  ],
  ["Rwanda", "Africa/Kigali"],
  ["Réunion", "Indian/Reunion"],
  ["Samoa", "Pacific/Apia"],
  ["San Marino", "Europe/San_Marino"],
  ["Sao Tome & Principe", "Africa/Sao_Tome"],
  ["Saudi Arabia", "Asia/Riyadh"],
  ["Senegal", "Africa/Dakar"],
  ["Serbia", "Europe/Belgrade"],
  ["Seychelles", "Indian/Mahe"],
  ["Sierra Leone", "Africa/Freetown"],
  ["Singapore", "Asia/Singapore"],
  ["Slovakia", "Europe/Bratislava"],
  ["Slovenia", "Europe/Ljubljana"],
  ["Solomon Islands", "Pacific/Guadalcanal"],
  ["Somalia", "Africa/Mogadishu"],
  ["South Africa", "Africa/Johannesburg"],
  ["South Georgia & the South Sandwich Islands", "Atlantic/South_Georgia"],
  ["South Korea", "Asia/Seoul"],
  ["South Sudan", "Africa/Juba"],
  ["Spain", "Europe/Madrid", "Atlantic/Canary"],
  ["Sri Lanka", "Asia/Colombo"],
  ["St Barthelemy", "America/St_Barthelemy"],
  ["St Helena", "Atlantic/St_Helena"],
  ["St Kitts & Nevis", "America/St_Kitts"],
  ["St Lucia", "America/St_Lucia"],
  ["St Maarten (Dutch)", "America/Lower_Princes"],
  ["St Martin (French)", "America/Marigot"],
  ["St Pierre & Miquelon", "America/Miquelon"],
  ["St Vincent", "America/St_Vincent"],
  ["Sudan", "Africa/Khartoum"],
  ["Suriname", "America/Paramaribo"],
  ["Svalbard & Jan Mayen", "Arctic/Longyearbyen"],
  ["Sweden", "Europe/Stockholm"],
  ["Switzerland", "Europe/Zurich"],
  ["Syria", "Asia/Damascus"],
  ["Taiwan", "Asia/Taipei"],
  ["Tajikistan", "Asia/Dushanbe"],
  ["Tanzania", "Africa/Dar_es_Salaam"],
  ["Thailand", "Asia/Bangkok"],
  ["Togo", "Africa/Lome"],
  ["Tokelau", "Pacific/Fakaofo"],
  ["Tonga", "Pacific/Tongatapu"],
  ["Trinidad & Tobago", "America/Port_of_Spain"],
  ["Tunisia", "Africa/Tunis"],
  ["Turkey", "Europe/Istanbul"],
  ["Turkmenistan", "Asia/Ashgabat"],
  ["Turks & Caicos Is", "America/Grand_Turk"],
  ["Tuvalu", "Pacific/Funafuti"],
  ["U.S. Outlying Islands", "Pacific/Midway"],
  ["Uganda", "Africa/Kampala"],
  ["Ukraine", "Europe/Kyiv"],
  ["United Arab Emirates", "Asia/Dubai"],
  ["United Kingdom", "Europe/London"],
  ["Uruguay", "America/Montevideo"],
  ["Uzbekistan", "Asia/Tashkent"],
  ["Vanuatu", "Pacific/Efate"],
  ["Vatican City", "Europe/Vatican"],
  ["Venezuela", "America/Caracas"],
  ["Vietnam", "Asia/Ho_Chi_Minh"],
  ["Virgin Islands (UK)", "America/Tortola"],
  ["Virgin Islands (US)", "America/St_Thomas"],
  ["Wallis & Futuna", "Pacific/Wallis"],
  ["Western Sahara", "Africa/El_Aaiun"],
  ["Yemen", "Asia/Aden"],
  ["Zambia", "Africa/Lusaka"],
  ["Zimbabwe", "Africa/Harare"],
  ["Åland Islands", "Europe/Mariehamn"],
];

const CITY_LABELS = {
  "America/St_Johns": "St. John's",
  "America/Sao_Paulo": "São Paulo",
  "America/Noronha": "Fernando de Noronha",
  "America/Cancun": "Cancún",
  "America/Ciudad_Juarez": "Ciudad Juárez",
  "Asia/Ho_Chi_Minh": "Ho Chi Minh City",
  "Asia/Urumqi": "Ürümqi",
  "Australia/Lord_Howe": "Lord Howe Island",
  "Atlantic/Canary": "Canary Islands",
  "Atlantic/Azores": "Azores",
  "Pacific/Chatham": "Chatham Islands",
  "Pacific/Easter": "Easter Island",
  "Pacific/Galapagos": "Galápagos Islands",
};

function cityLabel(value) {
  return CITY_LABELS[value] || value.split("/").at(-1).replace(/_/g, " ");
}

export function isValidTimeZone(value) {
  if (typeof value !== "string" || !value) return false;
  try {
    new Intl.DateTimeFormat("en", { timeZone: value });
    return true;
  } catch {
    return false;
  }
}

export function detectTimeZone() {
  try {
    const value = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return isValidTimeZone(value) ? value : "UTC";
  } catch {
    return "UTC";
  }
}

export function getTimeZoneGroups(extraZones = []) {
  const groups = [
    {
      label: "United States",
      options: US_OPTIONS.map(([value, label]) => ({ value, label })),
    },
    {
      label: "UTC",
      options: [{ value: "UTC", label: "UTC — Coordinated Universal Time" }],
    },
    ...COUNTRY_ZONES.map(([label, ...zones]) => ({
      label,
      options: zones.map((value) => ({
        value,
        label: `${label} — ${cityLabel(value)}`,
      })),
    })).sort((a, b) => a.label.localeCompare(b.label, "en")),
  ];
  const seen = new Set();
  const validGroups = groups
    .map((group) => ({
      ...group,
      options: group.options.filter(({ value }) => {
        if (seen.has(value) || !isValidTimeZone(value)) return false;
        seen.add(value);
        return true;
      }),
    }))
    .filter((group) => group.options.length);
  const extras = [];
  for (const value of Array.isArray(extraZones) ? extraZones : []) {
    if (seen.has(value) || !isValidTimeZone(value)) continue;
    seen.add(value);
    extras.push({ value, label: `${cityLabel(value)} — ${value}` });
  }
  if (extras.length) {
    validGroups.push({
      label: "Your device or saved time zone",
      options: extras,
    });
  }
  return validGroups;
}
